import type {Metadata} from "next"
import {Inter} from "next/font/google"
import "./globals.css"
import "mapbox-gl/dist/mapbox-gl.css"
import {AuthProvider} from "@/contexts/AuthContext"

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Web-Based Social Geo-wiki",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} antialiased`}>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    )
}
