name: Lint

on:
    push:
        paths:
            - frontend/**

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Install dependencies
              run: |
                  npm ci --only=prod
                  npm install --save-dev @types/node
              working-directory: frontend

            - name: Run Lint
              run: npm run lint
              working-directory: frontend
