name: Code formatter - Prettier

on:
    push:
        paths:
            - "backend/**"
            - "frontend/**"

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2

            - name: Setup node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 20

            - name: Run Prettier on backend
              run: npx prettier --check .
              working-directory: backend

            - name: Run Prettier on frontend
              run: npx prettier --check .
              working-directory: frontend
